# Generated by Django 5.0.7 on 2024-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner_cell_info_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='icon',
            field=models.TextField(),
        ),
    ]
