# Generated by Django 5.0.7 on 2024-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cell_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='url',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
