# Generated by Django 5.0.7 on 2024-08-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cell_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='url',
        ),
    ]
